[package]
name = "chimiquizz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
macroquad = "0.3.25"
ears = "0.8.0"
named_tuple = "0.1"

[profile.dev.package.'*']
opt-level = 3
